### ISSUE TITLE
[Feature] Banner

### ISSUE THREAD

**Issue by musiur** [crescents-stack/sociomatic#13]
Figma: https://www.figma.com/file/I94vBZrvyiRS6dbZioKu6I/SocioMatic?type=design&node-id=117%3A12337&mode=design&t=2ov74jBxmyAwX3B7-1

![Image](https://github.com/crescents-stack/sociomatic/assets/99522246/90222d5a-3766-465a-a2a6-2733c1ecc339)

**Comment by corners2wall** [comment]
@musiur can I get this?

**Comment by musiur** [comment]
Fixes #13
