### ISSUE TITLE
[Feature] FAQ: Accordion

### ISSUE THREAD

**Issue by musiur** [crescents-stack/sociomatic#14]
Figma: https://www.figma.com/file/I94vBZrvyiRS6dbZioKu6I/SocioMatic?type=design&node-id=117%3A12337&mode=design&t=2ov74jBxmyAwX3B7-1

We have a molecule component inside component/molecules name SectionHead. Please reuse that for header text of FAQ. Rest of the portion should be build with customizing [ShadcnUI accordion](https://ui.shadcn.com/docs/components/accordion)

![Image](https://github.com/crescents-stack/sociomatic/assets/99522246/85d8746b-a22c-4b62-88d0-d49373a3ae6a)

**Comment by R4Rohit23** [comment]
Hii @musiur I would like to work on this feature.

**Comment by musiur** [comment]
Fixes #14
