### ISSUE TITLE
[Feature] Footer

### ISSUE THREAD

**Issue by musiur** [crescents-stack/sociomatic#7]

**Comment by msi117** [comment]
any design file for reference?

**Comment by musiur** [comment]
@msi117 yes! you can view this: https://www.figma.com/file/I94vBZrvyiRS6dbZioKu6I/SocioMatic?type=design&node-id=19%3A20&mode=design&t=2ov74jBxmyAwX3B7-1

**Comment by msi117** [comment]
> @msi117 yes! you can view this: https://www.figma.com/file/I94vBZrvyiRS6dbZioKu6I/SocioMatic?type=design&node-id=19%3A20&mode=design&t=2ov74jBxmyAwX3B7-1

Thanks, will be creating PR soon.

**Comment by musiur** [comment]
Fixes #7
